name: Chekout

name: Chekout

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
   runs-on: ubuntu-latest
   name: Check Via Action
    steps:
      - uses: actions/checkout@v2
       with: repository: ${{ github.repository }}

env:
  NOME_ARTEFATO: REPO
     - name: Chek
     name: ${{ env.NOME_ARTEFATO }}
     path: ./
