
name: Data Atual
on: [push]
branches: [ main ]
build_and_test:

jobs:
 jobs1:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
     - run: date

 jobs2:
   name: Windows
  runs-on: Windows-latest
    steps:
    - run: date
        
 jobs3:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - run: date

 jobs4:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - run: date
     
jobs4:  
    name: Jobs Final 
    runs-on: windows-latest
    needs: [jobs1, jobs2, jobs3]
    steps:
    - run: echo 'Final'

      
